---
version : '3.8'
services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    volumes:
      - diploma_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }}
      timeout: 3s
      retries: 10
      interval: 3s

  api:
    image: vladimirbodrin/diplom_work:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  collect_static:
    image: vladimirbodrin/diplom_work:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    env_file: .env
    entrypoint: ''
    volumes:
      - django_static:/code/static/
    command: python3 manage.py collectstatic -c --no-input


  frontend:
    image: sermalenk/skypro-front:lesson-34
    ports:
      - 80:80
    depends_on:
      - api
      - collect_static
    volumes:
      - django_static:/usr/share/nginx/html/static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes :
  diploma_pg_data:
  django_static:
