name: Build and deploy docker hub
on:
  push:
    branches:
      - 'master'
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: list dir
        run: ls -la
      - name: clone code
        uses: actions/checkout@v2
      - name: list dir 2
        run: ls -la
#    steps:
#      - name: clone code
#        uses: actions/checkout@v2
#      - name: docker build
#        run: docker build -t vbodrin/diplom_work:$GITHUB_REF_NAME-$GIT_HUB_RUN_ID .
#      - name: docker_login
#        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ DOCKERHUB_USERNAME }} --password-stdin
#      -name: docker push
#        run: docker push vladimirbodrin/diplom_work:$GITHUB_REF_NAME-$GIT_HUB_RUN_ID
