name: Build and deploy
on:
  push:
    branches:
      - 'master'
jobs:
  #  build_and_push:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: clone code
  #        uses: actions/checkout@v2
  #      - name: docker build
  #        run: docker build -t vladimirbodrin/diplom_work:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
  #      - name: docker_login
  #        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
  #      - name: docker push
  #        run: docker push vladimirbodrin/diplom_work:$GITHUB_REF_NAME-$GITHUB_RUN_ID

  deploy:
    runs-on: ubuntu-latest
    #    needs: build_and_push
    steps:
      - uses: action/checkout@v3
      - uses: anthonykgross/ansible-vault-cli-github-action@v1
        with:
          vault_key: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          command: "ansible-vault decrypt deploy/.env"
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERV_HOST }}
          username: ${{ secrets.SERV_USERNAME }}
          password: ${{ secrets.SERV_PASSWORD }}
          source: "deploy/*"
          target: "diploma_work"
          strip-components: 1
